name: REALEASE VERSION

on: workflow_dispatch

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: build dist
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
      - name: pnpm install
        run: |
          echo ${{github.ref}}
          pnpm install
      - name: Build
        run: |
          echo ${{github.workspace}}
          pnpm build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: apps/tools-site/dist
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: production deployment
    environment:
      name: Netlify
      url: ${{ steps.netlify.outputs.deploy-url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: apps/tools-site/dist
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: "apps/tools-site/dist"
          production-deploy: true
          enable-pull-request-comment: true
          enable-commit-comment: true
          enable-commit-status: true
          overwrites-pull-request-comment: true
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  release:
    runs-on: ubuntu-latest
    needs: deploy
    name: release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: dist-artifact
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./dist-artifact
          outPath: tools-site.tar.gz
      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{github.token}}
          name: v${{ steps.package-version.outputs.current-version}}
          tag_name: v${{ steps.package-version.outputs.current-version}}
          body_path: ./changelogs/v${{ steps.package-version.outputs.current-version}}.md
          discussion_category_name: Release
          files: tools-site.tar.gz
