name: 🔀 Sync mirror to Bitbucket

on: workflow_dispatch

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror
        continue-on-error: true
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_ACCESS_MIRROR_SYNC }}
        with:
          source-repo: ${{github.repositoryUrl}}
          destination-repo: ${{secrets.BITBUCKET_TOOL_FE_GIT}}
